#!/bin/bash

if [ -z "$(ls /etc/apt 2>/dev/null)" ]; then
    LINUX_DISTRO="centos"
else
    LINUX_DISTRO="ubuntu"
fi

function terraform_installation
{
    if [ "$LINUX_DISTRO" == "ubuntu" ]; then
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo 'deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main' | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update
        sudo apt-get install -y jq terraform
    elif [ "$LINUX_DISTRO" == "centos" ]; then
        sudo yum update -y
        sudo yum install -y yum-utils
        sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        sudo yum install -y terraform
    fi    
}

function jq_installation
{
    if [ "$LINUX_DISTRO" == "ubuntu" ]; then
        sudo apt-get update
        sudo apt-get install -y jq
    elif [ "$LINUX_DISTRO" == "centos" ]; then
        sudo yum update -y
        sudo yum install -y epel-release
        sudo yum install -y jq
    fi    
}

function ncp_iam_authenticator_installation
{
    curl -o ncp-iam-authenticator https://kr.object.ncloudstorage.com/nks-download/ncp-iam-authenticator/v1.0.5/linux/amd64/ncp-iam-authenticator
    chmod +x ncp-iam-authenticator
    sudo mkdir -p /usr/local/bin
    sudo mv ncp-iam-authenticator /usr/local/bin
}

function launch_terraform
{
    terraform init
    terraform apply -auto-approve
    CLUSTER_UUID=$(cat terraform.tfstate|jq .outputs.cluster_uuid.value -r)
    ncp-iam-authenticator create-kubeconfig --clusterUuid $CLUSTER_UUID --region KR
    mkdir -p ~/.kube
    mv kubeconfig-$CLUSTER_UUID.yaml ~/.kube/config
}

function how_to_use
{
    echo "installation scripts"
    echo "  terraform, tf          install terraform"
    echo "  jq                     install jq(json parser)"
    echo "  iam                    install ncp-iam-authenticator"
    echo "  init, i                apply this template"
    echo ""
    echo "NOTICE::"
    echo "  Please get README.md before you launch."
}

case "$1" in 
    terraform|tf)
        terraform_installation
    ;;
    
    jq)
        jq_installation
    ;;
    
    iam)
        ncp_iam_authenticator_installation
    ;;

    init|i)
        launch_terraform
    ;;

    *)
        how_to_use
    ;;
esac
